"use client";
import {ChangeEvent,FormEvent,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";

type Lang="en"|"es";
type LocationState=""|"checking"|"active"|"denied"|"unsupported"|"imprecise";
type Zone="Fresno"|"Tulare"|"Visalia"|"Madera"|"Bakersfield";

const zones:Zone[]=["Fresno","Tulare","Visalia","Madera","Bakersfield"];

const cats=[
  {id:"Automobiles",en:"Automobiles",es:"Automóviles",descEn:"Cars, trucks & local dealers",descEs:"Autos, camionetas y concesionarios",icon:"◉"},
  {id:"Furniture",en:"Furniture",es:"Muebles",descEn:"Home furniture & décor",descEs:"Muebles y decoración para el hogar",icon:"⌂"},
  {id:"Phones",en:"Phones",es:"Teléfonos",descEn:"Phones, accessories & service",descEs:"Teléfonos, accesorios y servicio",icon:"⌁"},
  {id:"Stereo Shops",en:"Stereo Shops",es:"Tiendas de Estéreos",descEn:"Audio systems & installation",descEs:"Sistemas de audio e instalación",icon:"♫"},
  {id:"Wheels and Tire Shops",en:"Wheels and Tire Shops",es:"Rines y Llantas",descEn:"Wheels, tires & service",descEs:"Rines, llantas y servicio",icon:"◒"}
];
const items=[
  {titleEn:"Late-model local automobile",titleEs:"Automóvil reciente local",price:"$18,900",place:"Fresno · 2 mi",zone:"Fresno",cat:"Automobiles",verified:true,image:"https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80"},
  {titleEn:"Mid-century lounge chair",titleEs:"Sillón moderno de mediados de siglo",price:"$240",place:"Fresno · 4 mi",zone:"Fresno",cat:"Furniture",verified:true,image:"https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=900&q=80"},
  {titleEn:"Premium wheel package",titleEs:"Paquete de rines premium",price:"$899",place:"Tulare · 3 mi",zone:"Tulare",cat:"Wheels and Tire Shops",verified:true,image:"https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=900&q=80"},
  {titleEn:"Local family SUV",titleEs:"SUV familiar local",price:"$22,500",place:"Tulare · 6 mi",zone:"Tulare",cat:"Automobiles",verified:true,image:"https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80"},
  {titleEn:"Solid wood dining set",titleEs:"Comedor de madera sólida",price:"$475",place:"Visalia · 2 mi",zone:"Visalia",cat:"Furniture",verified:true,image:"https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=900&q=80"},
  {titleEn:"Sport wheel and tire set",titleEs:"Juego deportivo de rines y llantas",price:"$1,050",place:"Visalia · 5 mi",zone:"Visalia",cat:"Wheels and Tire Shops",verified:true,image:"https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=900&q=80"},
  {titleEn:"Clean commuter automobile",titleEs:"Automóvil económico y limpio",price:"$14,800",place:"Madera · 3 mi",zone:"Madera",cat:"Automobiles",verified:true,image:"https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80"},
  {titleEn:"Modern accent chair",titleEs:"Sillón decorativo moderno",price:"$185",place:"Madera · 4 mi",zone:"Madera",cat:"Furniture",verified:true,image:"https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=900&q=80"},
  {titleEn:"Local pickup truck",titleEs:"Camioneta pickup local",price:"$26,900",place:"Bakersfield · 4 mi",zone:"Bakersfield",cat:"Automobiles",verified:true,image:"https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80"},
  {titleEn:"Custom wheel package",titleEs:"Paquete de rines personalizados",price:"$1,250",place:"Bakersfield · 7 mi",zone:"Bakersfield",cat:"Wheels and Tire Shops",verified:true,image:"https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=900&q=80"}
];
const copy={
 en:{browse:"Browse",account:"My account",signIn:"Sign in",post:"Post an item",useLocation:"Use my location",locationActive:"Location active ✓",locationChecking:"Finding location…",locationDenied:"Location unavailable",sellOn:"SELL ON ADLOCA",sellTitle:"Sell your product here.",exposure:"Get full landing-page or ½-page exposure.",full:"Full page",half:"½ page",sellerText:"Business or personal? Create a profile to upload and display what you are selling.",sellerProfile:"Create a seller profile",shopLocal:"SHOP CLOSER TO HOME",headline:"Local Listings by",headlineEm:"Local Businesses.",searchPlaceholder:"What are you looking for?",search:"Search",nearMe:"Near me",popular:"Popular:",startLocal:"START LOCAL",looking:"What are you looking for?",allCategories:"View all categories",near:"NEAR FRESNO COUNTY",fresh:"Fresh local finds",shown:"listings shown",verified:"Location verified",empty:"No matches yet. Try another search or category.",community:"POWERED BY LOCAL COMMUNITY",poleTitle:"Selling something? Post it where neighbors look.",poleText:"PolePost gets the word out. AdLoca gets it sold.",visitPole:"Visit PolePost",footer:"Local ads. Real locations. Safer exchanges.",newListing:"NEW LOCAL LISTING",postTitle:"Post an item",postIntro:"Sign in and verify your location before your listing can be posted.",itemTitle:"Item title",selling:"What are you selling?",category:"Category",choose:"Choose one",price:"Price",description:"Description",details:"Condition, details, pickup options…",publicLocation:"Public city, ZIP code or county",verifyAgain:"Verify location again",verifyMine:"Verify my location",locationRequired:"Required. Your exact coordinates are not displayed publicly.",checking:"Checking your location…",imprecise:"Location is too imprecise. Move near a window and try again.",permission:"Location permission is required to post an item.",notSupported:"Location is not supported on this device.",photos:"Photos",addPhoto:"Add photo",saving:"Saving…",saveListing:"Save verified listing",yourAccount:"Your AdLoca account",profileIntro:"Create a buyer, seller, or business advertising profile.",createAccount:"Create account",displayName:"Display name",yourName:"Your name",email:"Email address",password:"Password",passwordHint:"At least 8 characters",homeZip:"Home ZIP code",accountType:"Account type",personal:"Personal",businessAdvertiser:"Business advertiser",businessName:"Business name (optional)",yourBusiness:"Your business",wait:"Please wait…",continue:"Continue"},
 es:{browse:"Explorar",account:"Mi cuenta",signIn:"Iniciar sesión",post:"Publicar artículo",useLocation:"Usar mi ubicación",locationActive:"Ubicación activa ✓",locationChecking:"Buscando ubicación…",locationDenied:"Ubicación no disponible",sellOn:"VENDE EN ADLOCA",sellTitle:"Vende tu producto aquí.",exposure:"Obtén exposición de página completa o de ½ página.",full:"Página completa",half:"½ página",sellerText:"¿Negocio o particular? Crea un perfil para subir y mostrar lo que vendes.",sellerProfile:"Crear perfil de vendedor",shopLocal:"COMPRA CERCA DE CASA",headline:"Anuncios locales de",headlineEm:"negocios locales.",searchPlaceholder:"¿Qué estás buscando?",search:"Buscar",nearMe:"Cerca de mí",popular:"Popular:",startLocal:"COMIENZA LOCAL",looking:"¿Qué estás buscando?",allCategories:"Ver todas las categorías",near:"CERCA DEL CONDADO DE FRESNO",fresh:"Novedades locales",shown:"anuncios mostrados",verified:"Ubicación verificada",empty:"Aún no hay resultados. Prueba otra búsqueda o categoría.",community:"IMPULSADO POR LA COMUNIDAD LOCAL",poleTitle:"¿Vendes algo? Publícalo donde buscan tus vecinos.",poleText:"PolePost corre la voz. AdLoca lo vende.",visitPole:"Visitar PolePost",footer:"Anuncios locales. Ubicaciones reales. Intercambios más seguros.",newListing:"NUEVO ANUNCIO LOCAL",postTitle:"Publicar un artículo",postIntro:"Inicia sesión y verifica tu ubicación antes de publicar.",itemTitle:"Título del artículo",selling:"¿Qué estás vendiendo?",category:"Categoría",choose:"Elige una",price:"Precio",description:"Descripción",details:"Condición, detalles y opciones de entrega…",publicLocation:"Ciudad, código postal o condado público",verifyAgain:"Verificar ubicación otra vez",verifyMine:"Verificar mi ubicación",locationRequired:"Obligatorio. Tus coordenadas exactas no se muestran públicamente.",checking:"Verificando tu ubicación…",imprecise:"La ubicación no es precisa. Acércate a una ventana e inténtalo otra vez.",permission:"Se requiere permiso de ubicación para publicar.",notSupported:"Este dispositivo no admite ubicación.",photos:"Fotos",addPhoto:"Agregar foto",saving:"Guardando…",saveListing:"Guardar anuncio verificado",yourAccount:"Tu cuenta de AdLoca",profileIntro:"Crea un perfil de comprador, vendedor o negocio anunciante.",createAccount:"Crear cuenta",displayName:"Nombre visible",yourName:"Tu nombre",email:"Correo electrónico",password:"Contraseña",passwordHint:"Mínimo 8 caracteres",homeZip:"Código postal",accountType:"Tipo de cuenta",personal:"Personal",businessAdvertiser:"Negocio anunciante",businessName:"Nombre del negocio (opcional)",yourBusiness:"Tu negocio",wait:"Espera…",continue:"Continuar"}
};

export default function Home(){
 const [post,setPost]=useState(false),[profile,setProfile]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState("All"),[photos,setPhotos]=useState<string[]>([]),[toast,setToast]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[verifiedLocation,setVerifiedLocation]=useState<{latitude:number,longitude:number,accuracy:number}|null>(null),[locationStatus,setLocationStatus]=useState<LocationState>(""),[lang,setLang]=useState<Lang>("en"),[selectedZone,setSelectedZone]=useState<Zone>("Fresno"),[browseLocation,setBrowseLocation]=useState("Fresno, CA"),[browseLocationStatus,setBrowseLocationStatus]=useState<LocationState>("");
 const t=copy[lang];
 const categoryName=(id:string)=>{const c=cats.find(x=>x.id===id);return c?(lang==="es"?c.es:c.en):id};
 const visible=useMemo(()=>items.filter(x=>x.zone===selectedZone&&(filter==="All"||x.cat===filter)&&(lang==="es"?x.titleEs:x.titleEn).toLowerCase().includes(query.toLowerCase())),[query,filter,lang,selectedZone]);
 const changeZone=(zone:Zone)=>{setSelectedZone(zone);setBrowseLocation(`${zone}, CA`);setBrowseLocationStatus("");setFilter("All");setQuery("");requestAnimationFrame(()=>document.getElementById("browse")?.scrollIntoView({behavior:"smooth"}))};
 const upload=(e:ChangeEvent<HTMLInputElement>)=>setPhotos(p=>[...p,...Array.from(e.target.files||[]).map(URL.createObjectURL)].slice(0,4));
 const done=(message:string)=>{setPost(false);setProfile(false);setPhotos([]);setVerifiedLocation(null);setLocationStatus("");setToast(message);setTimeout(()=>setToast(""),3500)};
 const verifyLocation=()=>{setLocationStatus("checking");if(!navigator.geolocation){setLocationStatus("unsupported");return}navigator.geolocation.getCurrentPosition(({coords})=>{if(coords.accuracy>5000){setVerifiedLocation(null);setLocationStatus("imprecise");return}setVerifiedLocation({latitude:coords.latitude,longitude:coords.longitude,accuracy:coords.accuracy});setLocationStatus("active")},()=>{setVerifiedLocation(null);setLocationStatus("denied")},{enableHighAccuracy:true,timeout:12000,maximumAge:0})};
 const detectBrowseLocation=()=>{setBrowseLocationStatus("checking");if(!navigator.geolocation){setBrowseLocationStatus("unsupported");return}navigator.geolocation.getCurrentPosition(()=>{setBrowseLocation(t.nearMe);setBrowseLocationStatus("active")},()=>setBrowseLocationStatus("denied"),{enableHighAccuracy:false,timeout:10000,maximumAge:300000})};
 const locationMessage=locationStatus==="checking"?t.checking:locationStatus==="active"?`${t.verified} ✓`:locationStatus==="imprecise"?t.imprecise:locationStatus==="denied"?t.permission:locationStatus==="unsupported"?t.notSupported:t.locationRequired;
 const browseLocationMessage=browseLocationStatus==="checking"?t.locationChecking:browseLocationStatus==="active"?t.locationActive:browseLocationStatus?t.locationDenied:t.useLocation;
 const submitListing=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const response=await fetch("/api/listings",{method:"POST",body:new FormData(e.currentTarget)});const body=await response.json();setBusy(false);if(!response.ok){setError(body.error||"Could not save listing");if(response.status===401){setPost(false);setProfile(true)}return}done(lang==="es"?"Tu anuncio fue guardado para revisión.":"Your listing was saved for review.")};
 const submitAuth=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const form=new FormData(e.currentTarget),email=String(form.get("email")),password=String(form.get("password")),mode=String(form.get("mode"));const supabase=createClient();if(mode==="signin"){const {error:authError}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(authError){setError(authError.message);return}done(lang==="es"?"Sesión iniciada en AdLoca.":"Signed in to AdLoca.");return}const metadata={display_name:String(form.get("displayName")),home_zip:String(form.get("homeZip")),account_type:String(form.get("accountType")),business_name:String(form.get("businessName"))};const {data,error:authError}=await supabase.auth.signUp({email,password,options:{data:metadata,emailRedirectTo:`${location.origin}/auth/callback`}});setBusy(false);if(authError){setError(authError.message);return}done(data.session?(lang==="es"?"Cuenta de AdLoca creada.":"AdLoca account created."):(lang==="es"?"Revisa tu correo para confirmar tu cuenta.":"Check your email to confirm your AdLoca account."))};
 return <main lang={lang}>
  <header><div className="brand-zone"><a className="brand" href="#"><i>A</i><b>AdLoca<small>LOCAL ADS. REAL LOCATIONS.</small></b></a><label className="zone-picker"><span>⌖</span><select aria-label={lang==="es"?"Elige una zona":"Choose listing zone"} value={selectedZone} onChange={e=>changeZone(e.target.value as Zone)}>{zones.map(zone=><option key={zone} value={zone}>{zone}</option>)}</select></label></div><nav><a href="#browse">{t.browse}</a><a href="/account">{t.account}</a><a href="https://www.polepost.org">PolePost</a></nav><div className="header-controls"><button className="location-button" onClick={detectBrowseLocation}>⌖ <span>{browseLocationMessage}</span></button><button className="language-toggle" onClick={()=>setLang(lang==="en"?"es":"en")} aria-label={lang==="en"?"Cambiar a español":"Switch to English"}>{lang==="en"?"Español":"English"}</button><button className="plain" onClick={()=>{setError("");setProfile(true)}}>{t.signIn}</button><button className="button" onClick={()=>{setError("");setVerifiedLocation(null);setLocationStatus("");setPost(true)}}>＋ {t.post}</button></div></header>
  <section className="hero"><aside className="seller-callout"><span>{t.sellOn}</span><h2>{t.sellTitle}</h2><p>{t.exposure}</p><div><b>{t.full}</b><b>{t.half}</b></div><small>{t.sellerText}</small><button className="button" onClick={()=>{setError("");setProfile(true)}}>{t.sellerProfile}</button></aside><span className="kicker">● {t.shopLocal}</span><h1>{t.headline}<br/><em>{t.headlineEm}</em></h1><div className="search"><label>⌕ <input aria-label={t.search} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.searchPlaceholder}/></label><label>⌖ <input aria-label="Location" value={browseLocation} onChange={e=>setBrowseLocation(e.target.value)}/></label><a className="button" href="#browse">{t.search}</a></div><div className="popular">{t.popular} {cats.slice(0,4).map(c=><button key={c.id} onClick={()=>setQuery(lang==="es"?c.es:c.en)}>{lang==="es"?c.es:c.en}</button>)}</div></section>
  <section className="wrap"><div className="heading"><div><span className="kicker">{t.startLocal}</span><h2>{t.looking}</h2></div><button className="plain" onClick={()=>setFilter("All")}>{t.allCategories}</button></div><div className="categories">{cats.map(c=><button className={filter===c.id?"category active":"category"} onClick={()=>setFilter(c.id)} key={c.id}><i>{c.icon}</i><b>{lang==="es"?c.es:c.en}</b><small>{lang==="es"?c.descEs:c.descEn}</small><span>→</span></button>)}</div></section>
  <section className="wrap listings" id="browse"><div className="heading"><div><span className="kicker">{lang==="es"?`CERCA DE ${selectedZone.toUpperCase()}`:`NEAR ${selectedZone.toUpperCase()}`}</span><h2>{t.fresh}</h2></div><small>{visible.length} {t.shown}</small></div><div className="cards">{visible.map(x=><article key={x.titleEn}><div className="pic"><img src={x.image} alt=""/>{x.verified&&<span>{t.verified} ✓</span>}<button aria-label="Save">♡</button></div><div className="copy"><small>{categoryName(x.cat)}</small><h3>{lang==="es"?x.titleEs:x.titleEn}</h3><b>{x.price}</b><p>⌖ {x.place} {x.verified&&<strong className="verified-check" aria-label={t.verified}>✓</strong>}</p></div></article>)}</div>{!visible.length&&<div className="empty">{t.empty}</div>}</section>
  <section className="pole"><i>P</i><div><small>{t.community}</small><h2>{t.poleTitle}</h2><p>{t.poleText}</p></div><a href="https://www.polepost.org">{t.visitPole} ↗</a></section>
  <footer><span>AdLoca</span><p>{t.footer}</p><small>© 2026 AdLoca</small></footer>
  {toast&&<div className="toast">✓ {toast}</div>}
  {post&&<Modal close={()=>setPost(false)}><span className="kicker">{t.newListing}</span><h2>{t.postTitle}</h2><p>{t.postIntro}</p><form onSubmit={submitListing}><label>{t.itemTitle}<input name="title" required maxLength={120} placeholder={t.selling}/></label><div className="twocol"><label>{t.category}<select name="category" required defaultValue=""><option value="" disabled>{t.choose}</option>{cats.map(c=><option value={c.id} key={c.id}>{lang==="es"?c.es:c.en}</option>)}</select></label><label>{t.price}<input name="price" required type="number" min="1" step="0.01" placeholder="$ 0"/></label></div><label>{t.description}<textarea name="description" required maxLength={2000} rows={3} placeholder={t.details}/></label><label>{t.publicLocation}<input name="location" required maxLength={100} placeholder="93721 / Fresno County"/></label><div className={verifiedLocation?"location-verify verified":"location-verify"}><button type="button" onClick={verifyLocation}>{verifiedLocation?t.verifyAgain:t.verifyMine}</button><span>{locationMessage}</span></div><input type="hidden" name="latitude" value={verifiedLocation?.latitude??""}/><input type="hidden" name="longitude" value={verifiedLocation?.longitude??""}/><input type="hidden" name="locationAccuracy" value={verifiedLocation?.accuracy??""}/><label className="bot-field" aria-hidden="true">Leave this field empty<input name="companyWebsite" tabIndex={-1} autoComplete="off"/></label><fieldset><legend>{t.photos} <span>{photos.length}/4</span></legend><div className="uploads">{photos.map((src,i)=><div className="preview" key={src}><img src={src} alt="Uploaded item"/><button type="button" onClick={()=>setPhotos(photos.filter((_,n)=>n!==i))}>×</button></div>)}{photos.length<4&&<label className="upload">＋<small>{t.addPhoto}</small><input type="file" accept="image/*" multiple onChange={upload}/></label>}</div></fieldset>{error&&<p className="formerror">{error}</p>}<button disabled={busy||!verifiedLocation} className="button full">{busy?t.saving:t.saveListing}</button></form></Modal>}
  {profile&&<Modal close={()=>setProfile(false)}><div className="profile"><i className="bigpin">A</i><h2>{t.yourAccount}</h2><p>{t.profileIntro}</p></div><form onSubmit={submitAuth}><div className="authswitch"><label><input defaultChecked type="radio" name="mode" value="signup"/> {t.createAccount}</label><label><input type="radio" name="mode" value="signin"/> {t.signIn}</label></div><label>{t.displayName}<input name="displayName" placeholder={t.yourName}/></label><label>{t.email}<input name="email" required type="email" autoComplete="email" placeholder="you@example.com"/></label><label>{t.password}<input name="password" required minLength={8} type="password" autoComplete="current-password" placeholder={t.passwordHint}/></label><div className="twocol"><label>{t.homeZip}<input name="homeZip" placeholder="93721" pattern="[0-9]{5}(-[0-9]{4})?"/></label><label>{t.accountType}<select name="accountType"><option value="personal">{t.personal}</option><option value="business">{t.businessAdvertiser}</option></select></label></div><label>{t.businessName}<input name="businessName" placeholder={t.yourBusiness}/></label>{error&&<p className="formerror">{error}</p>}<button disabled={busy} className="button full">{busy?t.wait:t.continue}</button></form></Modal>}
 </main>
}
function Modal({children,close}:{children:React.ReactNode,close:()=>void}){return <div className="backdrop" onMouseDown={close}><section className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={close}>×</button>{children}</section></div>}
